version: "3.4"

services:
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000

  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    env_file:
      - ./server/.env
    ports:
      - 5000:5000
