version: "3.4"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:80"

  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
